#!/bin/sh
#2.1 框架图
	-->PREROUTING-->[ROUTE]-->FORWARD-->POSTROUTING-->
	    mangle	 |	mangle		^mangle
	    nat		 |	filter		|nat
			 |			|
			 |			|	
			 v			|
			 INPUT			OUTPUT
			 |mangle		^mangle
			 |filter		|nat
			 v ------->local------->|filter
#2.2 链和表
	#表
		filter:	用于过滤的时候
		nat:	用于做NAT的时候（NAT:Network Address Translator）
	#链
		INPUT:		位于filter表，匹配目的IP是本机的包
		FORWORD:	位于filter表，匹配穿过本机的数据包
		PREROUTING:	位于nat表，用于修改目的地址（DNAT）	
		POSTROUTING:	位于nat表，用于修改源地址（SNAT）
#3.1 iptables语法概述
	#iptables [-t 要操作的表]
		<操作命令>
		[要操作的链]
		[规则号码]
		[规则条件]
		[-j 匹配到以后的动作]
#3.2 命令概述
	操作命令（-A，-I，-D，-R，-P，-F）
	查看命令（-[vnx]L）
	#-A <链名>	APPEND，追加一条规则（放到最后）
		eg. iptables -t filter -A INPUT -j DROP
	#-I <链名>[规则号码]	INSERT，插入一条规则
		eg. iptables -I INPUT -j DROP	#在filter表的INPUT链里插入一条规则（插入到第一条）
		eg. iptables -I INPUT 3 -j DROP	#在filter表的INPUT链里插入一条规则（插入到第三条）
	#注意：	1. -t filter可不写，不写则自动默认是filter表
		2. -I 链名[规则号码]，如果不写规则号码，则默认是1
		3. 确保规则号码<=(已有规则数+1)，否则报错
	#-D <链名><规则号码 | 具体规则内容>	DELETE，删除一条规则
		eg. iptables -D INPUT 3 (按号码匹配)	#删除filter表INPUT链中的第三条规则（不管\
			#它的内容是什么）
		eg. iptables -D INPUT -s 192.168.0.1 -j DROP (按内容匹配)	#删除filter表INPUT\
			#链中内容为“-s 192.168.0.1 -j DROP”的规则（不管其位置在哪里）
		#注意：	1. 若规则列表中有多条相同的规则时，按内容匹配只删除序号最小的一条
		#	2. 按号码匹配删除时，确保规则号码<=已有规则数，否则报错 
		#	3. 按内容匹配规则时，确保规则存在，否则报错
	#-R <链名><规则号码><具体规则内容>	REPLACE，替换一条规则
		eg. iptables -R INPUT 3 -j ACCEPT	#将原来编号为3的规则内容替换为“-j ACCEPT”
		#注意：	确保规则号码<=已有规则数，否则报错
	#-P <链名><动作>	POLICY，设置某个链的默认规则
		eg. iptables -P INPUT DROP	#设置filter表INPUT链的默认规则是DROP
		#注意：	当数据包没有被规则列表里的任何规则匹配到时，按此默认规则处理
	#-F <链名>	FLUSH，清空规则
