#!/bin/sh
operation=$1
script_dir=/home/supertool/AdMonitor/svn/Arbiter
#svn_dir=/home/supertool/AdMonitor/svn/Arbiter
for i in (51,52,53,54)
do
	ssh 192.168.1.$i
	svn up $script_dir
	$script_dir/move.sh $operation
done
