#!/bin/bash
#set nowrap
#set textwidth=111

------vim、gvim在windows下中文乱码的终极解决方案
------vim操作
------vim的标签功能
------vim多行操作(缩进、注释)
------退出vim时自动保存当前vim窗口的状态 重新打开后恢复原来状态

#vim、gvim在windows下中文乱码的终极解决方案

	set encoding=utf-8
	set fileencodings=utf-8,chinese,latin-1
	if has("win32")
	set fileencoding=chinese
	else
	set fileencoding=utf-8
	endif
	"解决菜单乱码
	source $VIMRUNTIME/delmenu.vim
	source $VIMRUNTIME/menu.vim
	"解决consle输出乱码
	language messages zh_CN.utf-8
#vim操作
	:e filename		打开文件进行编辑
	:w			保存文件
	/word			从上至下搜索关键词
	?wordd			从下至上搜索关键词
	/jo[ha]n		搜索john或者joan
	/fred\|joe		搜索fred或者joe
	/^\n/{2}		搜索2行空行
	:%s/old/new/g		替换所有的old为new
	:%s/old/new/gw		替换所有的Old为new前先确认
	:%s/old/new/gi		替换所有的olg为new，忽略大小写
	:%s/^/hello/g		在所有行的开始插入hello
	:%s/\r//g		删除dos格式的换行符(^M)

	:sp[lit]		水平切分窗口
	:vs			垂直切分窗口
	ctrl+w njhl		多窗口间切换
	ctrl+w ctrl+w		切换到下一个窗口
	ctrl+w [NUM]-+		调整水平窗口的大小
	ctrl+w [NUM]<>		调整垂直窗口的大小

	:cd ..			切换到上一层目录
	:e ..			进入上一层目录
	:!pwd			执行外部的pwd命令，回车返回当前vim
	:sh			临时切换到terminal，exit返回当前vim

	:tabnew			创建新标签页
	:tabn			切换到下一个标签页
	:tabp			切换到上一个标签页
	:tabfirst | tablast	切换到第一个|最后一个标签页
	
#vim的标签功能
	:tabnew			在当前标签页之后打开带空窗口的新标签页
	:tabc[lose]		关闭当前标签页
	:tabc[lose] {count}	关闭第{count}个标签页
	:tabo[nly]		关闭所有其他的标签页
	:tabn[ext] {count}	转到下一个标签页。最后一个标签页则回绕到第一个,{count}可选
	:tabp[revious] {count}	转到前一个标签页。首个标签页则回绕到最后一个，{count}可选
	:tabfir[st]		转到第一个标签页
	:tabl[ast]		转到最后一个标签页
	:tabs			列出标签页和它们包含的窗口
				当前窗口显示">"
				修改过的缓冲区显示"+"
	:tabm[ove] [N]		把当前标签页移到第N个标签页之后。第一个标签页的编号为0，如果没有\
					N，当前标签页被移动到最后一个
	:tabd[o] {cmd}		对每个标签页执行 {cmd}
				只对每个标签页的当前窗口进行操作。如果某个标签页出现错误，不再继续访问其余的标签页
				{cmd}可以包含'|'以连接多个命令
				{cmd}不能打开标签页、关闭标签页或重排标签页
	:{count}gt		转到第{count}个标签页。首个标签页编号为1
	:{count}gT		转到前面{count}个标签页，首个标签页则回绕到最后一个
#vim多行操作(缩进、注释)
	#多行缩进
	1.按v进入visual状态，选择多行，用>或<缩进或缩出
	2.通常根据语言特征使用自动排版功能：在当前状态下对当前行用==，或对多行使用n==表示自动缩进从当前行起的向下n行，相当于IDE里面的code formart。使用gg=G可以对整篇代码进行排版。
	#多行注释
	1.ctrl+v进入列编辑模式，上下移动光标，选择多行，然后按大写的I，再插入注释符，比如'#'，再按Esc，就会全部注释了。
	2.使用sed进行多行操作
	  :line1,line2s/^/#/
	#取消多行注释
	1.先按v，进入visual模式，选中多列，然后按ctrl+v进入列选择模式，上下选择多行。然后按d删除选中部分。
	2.使用sed对多行进行操作。
	  :line1,line2s/#//
#退出vim时自动保存当前vim窗口的状态 重新打开后恢复原来状态
	在你的/etc/vim/gvimrc或/etc/vim/gvimrc.local中加入以下两行（在vim的配置文件中加入即可）
	au VimLeave * exe 'if exists("g:cmd") && g:cmd == "gvims" | if strlen(v:this_session) | exe "wviminfo! " . v:this_session . ".viminfo" | else | exe "wviminfo! " . "~/.vim/session/" . g:myfilename . ".session.viminfo" | endif | endif '
	au VimLeave * exe 'if exists("g:cmd") && g:cmd == "gvims" | if strlen(v:this_session) | exe "mksession! " . v:this_session | else | exe "mksession! " . "~/.vim/session/" . g:myfilename . ".session" | endif | endif'
	
	并保证目录~/.vim/session存在
	然后写一个脚本程序gvims
	#!/bin/sh
	if [ -r ~/.vim/session/$1.session ]; then
		gvim "+source ~/.vim/session/$1.session" "+rviminfo ~/.vim/session/$1.session.viminfo" "+let g:cmd = \"gvims\" " "+command Noprj let g:cmd = \"\" "
	else
		gvim "+let g:myfilename = \"$1\" " "+let g:cmd = \"gvims\" " "+command Noprj let g:cmd = \"\" "
	fi
	
	当用gvim编辑完后，退出时，文件是以当前子窗口的名字保存窗口信息的，所以下次打开时，要用到那个窗口名字作为gvim的参数

