#!/bin/usr/python

#chapter 3
	#python的转义序列
		\	newline Ignored忽略换行符
		\\	Backslash反斜杠
		\'	Single quote单引号	'
		\"	Double quote双引号	"
		\a	ASCII Bell响铃
		\b	ASCII backspace退格
		\f	ASCII form fedd表格换行
		\n	ASCII line feed换行
		\N{name}	Unicode数据库中命名的字符（尽Unicode字符串）
		\r	ASCII carriage return回车
		\t	ASCII horizontal tab水平制表符
		\uxxxx	16位十六进制值表示的字符（仅Unicode）
		\Uxxxxxxxx	32位十六进制表示的字符（仅Unicode）
		\v	ASCII vertical tab 垂直制表符
		\ooo	八进制值表示的字符
		\xhh	十六进制值表示的字符
	#in & not in
		检查一个字符串是否是另一个字符串的一部分
	#find() & index()
		子串在字符串中出现的位置
			#若不是某字符串的子串，find()返回-1,index()抛出ValueError异常
	#string[index:] & string[:index]
		查找从index开始到string结尾的每一个字符，& 查找从string开始到index所在位子的所有字符
	#split() & splitlines() & join()
		根据某个指定的分隔符对一个字符串进行提取
		()内可以放0,1,2个参数
		splitlines()用于分割多行文本
		join()用于连接多个字符串	注：如果传递给join()的是一系列整数，需要稍作改变（P93）
	#replace()
		用于创建和修改文本字符
		与切分操作以及strip()方法一样，replace()会创建一个新字符串，而不是对字符串进行行内修改
	#unicode
		python可以对unicode进行处理
	
