#! /usr/bin/env python

#re正则表达式
	'|'	或规则
		在[]中它不表示或，而表示它本身的字符。也可以使用"\ "表示它本事
		它的有效范围是它两边的整条规则，比如'dog|cat'匹配的是"dog或cat"，而不是"g和c"。如果
			要想限定它的有效范围，必须使用一个无捕获组"(?:)"包起来, 比如要匹配"I have a dog"和
			"I have a cat"，需要写成"I have a (?:dog|cat)"
